# Affine Function

## 1-1 Affine Function with 1 Feature

### code.1-1-1 : Affine Function

In [4]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) #input setting !! input은 matrix형태로 넣어줘야한다.
print(x)

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)


In [10]:
dense = Dense(units = 1, activation = "linear") #imp. unit이 하나인 an affine function 즉, z = x*w +b 를 만들어준다.

y_tf = dense(x) # 연산 진행 Z = x * W + B 형태

W, B = dense.get_weights() #만약 dense연산을 실행하기 전 즉, y_tf 객체를 구성하기 전에 W,B를 뽑으려 하면, 아직 할당되지 않아 오류가 나온다.

y_man = tf.linalg.matmul(x,W) + B #forward propagation(manual)

#y_tf인 tensorflow에 있는 dense연산으로 진행한 것이 실제로 연산이 잘 작동되는지 확인하기 위해 y_man 객체를 만들어 직접연산을 해봤다.
# matmul()는 matrix multify. 즉, matrix형태를 곱하는 것

#print results
print("===== Input/Weight/Bias=====")
print("x:{}\n{}\n".format(x.shape,x.numpy()))
print("W:{}\n{}\n".format(W.shape,W))
print("B:{}\n{}\n".format(B.shape,B))

print("===== Outputs =====")
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape,y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape,y_man.numpy()))
# tensorflow에 dense연산이 직접 연산해본 manual과 동일한 결과를 보여줌을 알 수 있다.

===== Input/Weight/Bias=====
x:(1, 1)
[[10.]]

W:(1, 1)
[[1.0235344]]

B:(1,)
[0.]

===== Outputs =====
y(Tensorflow): (1, 1)
[[10.235344]]

y(Manual): (1, 1)
[[10.235344]]



### code.1-1-1 : Params Initialization

In [17]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant #내가 원하는 값으로 initialize 해준다.

x = tf.constant([[10.]]) #input setting !! input은 matrix형태로 넣어줘야한다.

#weight/bias setting
w, b = tf.constant(10.), tf.constant(20.) #tensorflow는 기본적으로 floating point 32byte를 사용하기때문에 숫자뒤에 .을 붙이는 습관을 들이자.
w_init, b_init = Constant(w), Constant(b) #keras.initialize.Constant()를 import를 활용해 Constant만 작성.

# imp. an affine function
dense = Dense(units = 1,
             activation='linear', #activation function은 linear로 일단 설정해보자.
             kernel_initializer = w_init,
             bias_initializer=b_init)
y_tf =dense(x)
print(y_tf) # x = 10., w = 10. b = 20. 으로 10 X 10 +20ㅇ
W,B = dense.get_weights()

#print results
print("W :{}\n{}\n".format(W.shape,W))
print("B :{}\n{}\n".format(B.shape,B))

#parmas Initialization은 내가 가고자하는 방향으로 이 모델이 잘 작동하는지 내가 임의로 W,B를 정하여 진행과정을 확인해보고 싶을 때 사용한다.

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W :(1, 1)
[[10.]]

B :(1,)
[20.]



## 1-2:Affine Functions with n Features

### code.1-2-1:Affine Functions with n Features

In [19]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape =(1,10),minval=0,maxval=10)

dense = Dense(units=1)

y_tf = dense(x) #Dense에서 w,b가 몇개 필요한지 말하지 않아도 dense를 통과하면 자기 스스로 w와 b가 몇개 필요한지 확인해서 초기화 시킨다.

W,B = dense.get_weights() #그 초기화 시켜서 할당한 W와 B를 꺼내서

y_man = tf.linalg.matmul(x,W)+B #matmul를 활용해 직접 계산한다.

#print results
print("===== Input/Weight/Bias=====")
print("x:{}\n{}\n".format(x.shape,x.numpy()))
print("W:{}\n{}\n".format(W.shape,W))
print("B:{}\n{}\n".format(B.shape,B))

print("===== Outputs =====")
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape,y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape,y_man.numpy()))
#그결과, 동일한 dense값과 manual값임을 알 수 있다.

===== Input/Weight/Bias=====
x:(1, 10)
[[7.954689   0.30616045 0.4393041  9.93988    8.966143   4.121319
  0.97882986 0.835197   8.333364   7.9065084 ]]

W:(10, 1)
[[ 0.43643647]
 [-0.69332606]
 [-0.67365944]
 [ 0.7296687 ]
 [ 0.58583814]
 [-0.12978977]
 [-0.5939662 ]
 [-0.61518216]
 [ 0.49237043]
 [ 0.4293198 ]]

B:(1,)
[0.]

===== Outputs =====
y(Tensorflow): (1, 1)
[[21.336462]]

y(Manual): (1, 1)
[[21.336462]]

