# Artificial Neurons

## 1-3: Activation Functions

Artificial Neurons를 구현할때,

Affine Function뒤에 바로 Activation Function이 따라오는 게 가장 이상적이지만,

딥러닝이 심화되면 이 두개 사이에 또다른 연산들이 들어갈 수 있어서 이런 상황을 대비하기 위해

Activation Function만 만드는 것과 Affine Function과 같이 만드는 것 두가지 모두 살펴보자.

### Code.1-3-1: Activation Layers

In [10]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation #activation 식을 layer로 가져왔다.

x = tf.random.normal(shape=(1,5)) #input setting

#imp.activation function
sigmoid = Activation("sigmoid")
tanh = Activation("tanh")
relu = Activation("relu")

#forward propagation(tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

#forward propagation(manual)
y_sigmoid_man = 1 /(1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x)+exp(-x))
y_relu_man = maximum(x,0)

print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(menual): {}\n{}\n".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("tand(Tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("tand(menual): {}\n{}\n".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("relu(Tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("relu(menual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

#아래 결과를 보면 tensorflow로 구현한 것과 직접 activation function들의 식으로 구현한 것과 동일한 값이 나오는 것을 알 수 있다.
#하나를 구현해보더라도 직접구현하는 습관이 중요.!

x: (1, 5)
[[ 0.43158635 -0.06011844  1.0767578   0.05733462 -0.16877407]]

Sigmoid(Tensorflow): (1, 5)
[[0.60625243 0.48497495 0.74587995 0.51432973 0.45790637]]
Sigmoid(menual): (1, 5)
[[0.60625243 0.48497495 0.74587995 0.51432973 0.45790637]]

tand(Tensorflow): (1, 5)
[[ 0.4066462  -0.06004617  0.7919937   0.05727187 -0.16718969]]
tand(menual): (1, 5)
[[ 0.40664616 -0.06004611  0.79199374  0.05727186 -0.16718967]]

relu(Tensorflow): (1, 5)
[[0.43158635 0.         1.0767578  0.05733462 0.        ]]
relu(menual): (1, 5)
[[0.43158635 0.         1.0767578  0.05733462 0.        ]]


### Code.1-3-2: Activation in Dense Layer

In [18]:
#아래 코드는 Affine Function과 Activation Function이 동시에 Dense로 한번에 진행되는 코드다.
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape = (1,5)) #input setting

#imp. artificial neurons
dense_sigmoid = Dense(units=1,activation="sigmoid")
dense_tanh = Dense(units=1,activation="tanh")
dense_relu = Dense(units=1,activation="relu")

#forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with Sigmoid: {}\n{}".format(y_sigmoid.shape,y_sigmoid.numpy()))
print("AN with tanh: {}\n{}".format(y_tanh.shape,y_tanh.numpy()))
print("AN with relu: {}\n{}".format(y_relu.shape,y_relu.numpy()))

#forward propagation(manual)
print("\n==============\n")

W, b = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x,W) + b #z 는 affine Function을 계산한 값이다.
a = 1/ (1+exp(-z))
print("Activation value(Tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation value(menual): {}\n{}".format(a.shape, a.numpy()))
# 위 두 코드의 결과값이 같다는 의미는 Dense(units=1,activation="sigmoid")가 affine을 계산한 후에 바로 activation을 연산하였다는 것이다.

AN with Sigmoid: (1, 1)
[[0.7773026]]
AN with tanh: (1, 1)
[[0.8482881]]
AN with relu: (1, 1)
[[1.250016]]


Activation value(Tensorflow): (1, 1)
[[0.7773026]]
Activation value(menual): (1, 1)
[[0.7773026]]


## 1-4: Artificial Neurons

### Code.1-4-1: Artificial Neurons

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = input("which do you want activation Function?")
#activation ="sigmoid"
#activation ="tanh"
#activation = 'relu'

x = tf.random.uniform(shape=(1,10)) #input setting

dense = Dense(units=1,activation = activation) #imp.. an affine + activation

y_tf = dense(x)
W,b = dense.get_weights()
print("W:{}\n{}\n".format(W.shape,W))
print("b:{}\n{}\n".format(b.shape,b))

#calculate activation value manually
y_man = tf.linalg.matmul(x,W)+b
if activation =="sigmoid":
    y_man_activation = 1/(1+exp(-y_man))
elif activation == "tanh":
    y_man_activation = (exp(y_man)-exp(-y_man))/(exp(y_man)+exp(-y_man))
elif activation == "relu":
    y_man_activation = maximum(y_man,0)
    
print("\nActivation:",activation)
print("y_tf: {}\n{}\n".format(y_tf.shape,y_tf.numpy()))
print("y_man: {}\n{}\n".format(y_man_activation.shape,y_man_activation.numpy()))

#꼭 이런 모델들이 어떻게 작동되는지 확인해보고 검증해보는 과정을 밟는 습관을 들이자.

which do you want activation Function?relu
W:(10, 1)
[[ 0.11144274]
 [ 0.6026682 ]
 [ 0.08686566]
 [-0.46665496]
 [-0.08183372]
 [ 0.68314713]
 [-0.40873873]
 [-0.2919103 ]
 [-0.23367286]
 [ 0.6926189 ]]

b:(1,)
[0.]


Activation: relu
y_tf: (1, 1)
[[1.606822]]

y_man: (1, 1)
[[1.606822]]



## 1-5: Minibatches

### Code.1-5-1: Shapes of Dense Layers

In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 32000,10 #set input params
x = tf.random.normal(shape=(N,n_feature)) #minibatch 생성 x는 matrix형태로 이론에서 공부했던, (x)T형태의 모형이다.

dense = Dense(units = 1, activation = "relu") #imp. an AN
y = dense(x) #forward propagation

W, b = dense.get_weights() #get weight/bias

#print resluts
print("Shape of x: ",x.shape)
print("Shape of W: ",W.shape)
print("Shape of b: ",b.shape)
print("Shape of y: ",y.shape)

#입력되는 matrix x의 개수와 상관없이 W와 b값은 변함이 없다. 

Shape of x:  (32000, 10)
Shape of W:  (10, 1)
Shape of b:  (1,)
Shape of y:  (32000, 1)


### Code.1-5-2: Output Calculations

In [35]:
#위 코드에 이어서 activation Function까지 연산하는 거까지 한거임.
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8,10 #set input params
x = tf.random.normal(shape=(N,n_feature)) #minibatch 생성 x는 matrix형태로 이론에서 공부했던, (x)T형태의 모형이다.

dense = Dense(units = 1, activation = "sigmoid") #imp. an AN
y_tf = dense(x) #forward propagation(tensorflow)

W,b = dense.get_weights() #get weight/bias

y_man = tf.linalg.matmul(x,W)+b #forward propagation(Manual)
y_man_activation = 1/(1+tf.math.exp(-y_man))

#print results
print("Output(tensorflow): \n",y_tf.numpy())
print("Output(manual): \n",y_man_activation.numpy())


Output(tensorflow): 
 [[0.75885034]
 [0.6597462 ]
 [0.619539  ]
 [0.46651772]
 [0.8563878 ]
 [0.35026667]
 [0.6869893 ]
 [0.5353104 ]]
Output(manual): 
 [[0.75885034]
 [0.6597462 ]
 [0.619539  ]
 [0.46651772]
 [0.8563878 ]
 [0.35026667]
 [0.6869893 ]
 [0.5353104 ]]
