# 2-1 Dense Layers

코딩 과정
dense layers 진행과정과 진행하면서 변화되는 입력데이터의 shape와 weight, bias의 shape도 확인해보자.
1. x입력데이터는 tf.random.normal로 shape를 설정하여 만들자.
2. dense 패키지를 활용하여 affine과 activation을 동시에 연산을 진행하는 객체를 만들고 거기에 x입력값을 넣자.
3. 연산 다 된 상태에서 이제 W, B와 마지막으로 나온 출력값의 shape들을 확인해보자.


## Code.2-1-1:Shapes of Dense Layers

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4,10 #N은 데이터의 행개수, n_feature은 특성 즉 열의 개수
X = tf.random.normal(shape=(N,n_feature))

n_neuron = 3
dense = Dense(units = n_neuron, activation = "sigmoid")
Y_tf = dense(X)

W, B = dense.get_weights()

print('==== Input/Weight/Bias ====')
print('X: ', X.shape)
print('W: ', W.shape)
print('B: ', B.shape)
print('Y: ', Y_tf.shape)
print(Y_tf)

==== Input/Weight/Bias ====
X:  (4, 10)
W:  (10, 3)
B:  (3,)
Y:  (4, 3)
tf.Tensor(
[[0.30593953 0.2792285  0.73360217]
 [0.588831   0.22446041 0.6682987 ]
 [0.34605026 0.81149256 0.7125092 ]
 [0.5924157  0.50329536 0.6592485 ]], shape=(4, 3), dtype=float32)


## Code.2-1-2: Output Calculations (실제 연산으로 진행해보자)

In [27]:
import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4,10 #N은 데이터의 행개수, n_feature은 특성 즉 열의 개수
X = tf.random.normal(shape=(N,n_feature))

n_neuron = 3
dense = Dense(units = n_neuron, activation = "sigmoid")
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow):\n",Y_tf.numpy())

#calculate with matrix multiplication - 메트릭스 형태로 바로 곱을 하는 것.
Z = matmul(X, W)+B
Y_man_matmul= 1/(1+exp(-Z))
print("Y(with multiplication): \n", Y_man_matmul.numpy())

#calculate with dot products - dot product형태로 곱을하여 Yo_man_vec에 모두 모은 것.
Y_man_vec = np.zeros(shape=(N, n_neuron))
#print(Y_man_vec,"가 아래처럼변함")
for x_idx in range(N):
    x = X[x_idx]
    
    for nu_idx in range(n_neuron):
        w, b = W[:,nu_idx],B[nu_idx]
        z = tf.reduce_sum(x *w)+b
        
        a = 1/(1+exp(-z))
        Y_man_vec[x_idx,nu_idx] = a #Y_man_vec metrix에 a값을 입력시켜준다. 행위치는 x_idx, 열위치는 nu_idx다.
        
print("Y(with dot products): \n", Y_man_vec)

#하나하나의 과정들을 볼수 있다.

Y(Tensorflow):
 [[0.43203837 0.05802592 0.50114614]
 [0.47051385 0.04984962 0.2801825 ]
 [0.17265202 0.752611   0.45432004]
 [0.7772887  0.54309726 0.30602607]]
tf.Tensor(
[[0.43203837 0.05802592 0.50114614]
 [0.47051385 0.04984962 0.2801825 ]
 [0.17265202 0.752611   0.45432004]
 [0.7772887  0.54309726 0.30602607]], shape=(4, 3), dtype=float32)
Y(with multiplication): 
 [[0.43203837 0.05802592 0.50114614]
 [0.47051385 0.04984962 0.2801825 ]
 [0.17265202 0.752611   0.45432004]
 [0.7772887  0.54309726 0.30602607]]
Y(with dot products): 
 [[0.43203831 0.05802592 0.50114614]
 [0.47051391 0.04984962 0.28018251]
 [0.17265199 0.75261092 0.4543201 ]
 [0.77728868 0.54309726 0.30602607]]


# 2-2: Cascaded Dense Layers

## Code.2-2-1: Shapes of Cacaded Dense Layers

In [38]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
N, n_features =4, 10
X = tf.random.normal(shape=(N,n_feature))

n_neurons = [3,5]
dense1 = Dense(units = n_neurons[0], activation = 'sigmoid')
dense2 = Dense(units = n_neurons[1], activation = 'sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

#get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("X : {}\n".format(X.shape))

print("W1 : {}".format(W1.shape))
print("B1 : {}".format(B1.shape))
print("A1 : {}\n".format(A1.shape))

print("W2 : {}".format(W2.shape))
print("B2 : {}".format(B2.shape))
print("Y : {}\n".format(Y.shape))

X : (4, 10)

W1 : (10, 3)
B1 : (3,)
A1 : (4, 3)

W2 : (3, 5)
B2 : (5,)
Y : (4, 5)



## Code.2-2-2: Dense Layers with python List

In [5]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features =4, 10
X = tf.random.normal(shape=(N,n_feature))
print("input:", X.shape)

n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units = n_neuron, activation = "relu")
    dense_layers.append(dense)
#dense_layer에는 dense자체가 들어가있다. print(dense_layers)

for dense_idx, dense in enumerate(dense_layers):
#enumerate는 for문에서 활용하는데, (list)안에 있는 것을 (idex,원소)로 형성하여 tuble형태로 만들어준다.
    X = dense(X) #matrix형태의 X자체를 dense에 넣어 바로 연산을 진행한다.
    print("After dense layer", dense_idx)
    print(X.shape) #첫번째 layer에 들어갔다가 연산된 X를 출력한다.
Y = X

""" 진행 순서
1. 입력 X와 n_neurons값을 설정하여 정의한다.
2. dense_layers라는 list를 만든다.
3. n_neuron 리스트에 있는 값들을 활용해서 Dense매소드로 연산을 하는 dense를 통채로 dense_layers 리스트에 삽입한다.
4. 삽입된 각 layer의 연산들을 이제 입력값인 X를 넣어 연산해준다.
5. 연산되어 나온 값은 그 다음의 dense로 연산된다.
6. 그렇게 연속으로 쭉 for문을 활용하여 진행한다.
7. 진행되는 과정에서 사이에 print(dense_idx)와 print(X.shape)를 확인해본다.
"""
#확인하여 보면, 처음 입력된 X의 N값은 계속해서 행의 수로 지속되고, layer에 들어갔다 나오면, layer의 neuron개수로 열의 수가 변하는 것을 확인할 수 있다.
#이유는, X(4x10) * W(10xneuron개수) -> X(4xneuron개수) 행렬의 곱을 생각해보면 이해할 수 있다.


input: (4, 10)
After dense layer 0
(4, 10)
After dense layer 1
(4, 20)
After dense layer 2
(4, 30)
After dense layer 3
(4, 40)
After dense layer 4
(4, 50)
After dense layer 5
(4, 60)
After dense layer 6
(4, 70)
After dense layer 7
(4, 80)
After dense layer 8
(4, 90)
After dense layer 9
(4, 100)


' 진행 순서\n1. 입력 X와 n_neurons값을 설정하여 정의한다.\n2. dense_layers라는 list를 만든다.\n3. n_neuron 리스트에 있는 값들을 활용해서 Dense매소드로 연산을 하는 dense를 통채로 dense_layers 리스트에 삽입한다.\n4. 삽입된 각 layer의 연산들을 이제 입력값인 X를 넣어 연산해준다.\n5. 연산되어 나온 값은 그 다음의 dense로 연산된다.\n6. 그렇게 연속으로 쭉 for문을 활용하여 진행한다.\n7. 진행되는 과정에서 사이에 print(dense_idx)와 print(X.shape)를 확인해본다.\n'

## Code.2-2-3: Output Calculations

In [107]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_features =4, 10 #4개의 데이터 셈플
X = tf.random.normal(shape=(N,n_feature))
X_cp = tf.identity(X) 
#X_cp=X로 해버리면 컴퓨터는 X_cp와 X의 주소값이 같다고 생각하여, 동일하게 계속 변동이 될것이므로, 따로 주소값을 두기위해 tf.identity로 뒀다.

n_neurons = [3,4,5]

dense_layers = list()

for n_neuron in n_neurons:
    dense = Dense(units = n_neuron, activation = "sigmoid")
    dense_layers.append(dense)
#dense_layer에는 dense자체가 들어가있다. print(dense_layers)

#forward propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X) 
    w,b = dense.get_weights()
    #Weight와 Bias값도 list를 만들어 각 리스트에 삽입시키자.
    W.append(w)
    B.append(b)
print("Y(Tensorflow): \n", X.numpy())
         
#forward propagation(Menual) menual 계산을 위해 위에 w와 b의 list를 만든것이다.
for layer_idx in range(len(n_neurons)):
    w,b  =W[layer_idx], B[layer_idx] #위에서 만든 W, B 리스트에서 neurons의 순서에 맞게 꺼내어 affine function 과 activation function을 진행한다.
    
    X_cp = matmul(X_cp,w)+b
    X_cp = 1/(1+exp(-X_cp))
print("T(Menual): \n", X_cp.numpy())


Y(Tensorflow): 
 [[0.25245297 0.46066585 0.4525585  0.45102328 0.5903147 ]
 [0.23759148 0.4002252  0.40926906 0.45166448 0.59273547]
 [0.24389961 0.46314526 0.44465926 0.44369826 0.5874325 ]
 [0.26002067 0.44658163 0.4542893  0.4591606  0.59370977]]
T(Menual): 
 [[0.25245297 0.46066585 0.4525585  0.45102328 0.5903147 ]
 [0.23759148 0.4002252  0.40926906 0.45166448 0.59273547]
 [0.24389961 0.46314526 0.44465926 0.44369826 0.5874325 ]
 [0.26002067 0.44658163 0.4542893  0.4591606  0.59370977]]
