# 3-4: Softmax Layers

## Code.3-4-1: IO of Softmax

In [9]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape = (1,5),minval=-10, maxval=10)

softmax_value = Activation('softmax')(logit)
print(softmax_value)
softmax_sum = tf.reduce_sum(softmax_value,axis=1) #축은 오른쪽 방향으로 향하며 더한다.
 
print("Logits :",logit.numpy())
print("Probabilities :",softmax_value.numpy())
print("Sum of softmax values :",softmax_sum) #probabilities를 다 더하면, 1이 나올 것이다.

tf.Tensor([[4.2436343e-02 7.4803221e-01 6.7954011e-02 2.0188669e-07 1.4157726e-01]], shape=(1, 5), dtype=float32)
Logits : [[ 5.8201838  8.689625   6.29101   -6.4356256  7.0250244]]
Probabilities : [[4.2436343e-02 7.4803221e-01 6.7954011e-02 2.0188669e-07 1.4157726e-01]]
Sum of softmax values : tf.Tensor([1.], shape=(1,), dtype=float32)


## Code.3-4-2: Softmax in Dense Layers

In [2]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape = (8,5),minval=-10, maxval=10)
dense = Dense(units = 8, activation = "softmax")
print(logit)
Y = dense(logit)
print(Y)
print(tf.reduce_sum(Y, axis = 1)) 
#8개의 값들이 전부다 1이 나온걸 알 수 있다. 

tf.Tensor(
[[ 0.6345415   6.9142685  -4.9067974   4.0511084   6.610758  ]
 [-8.227239   -3.092916   -5.404613   -1.6112404   2.0145702 ]
 [-0.23950768 -3.983605    4.3695593   8.127605    4.0134983 ]
 [ 2.9718542   3.8331556  -0.17416191 -2.990477    3.9756374 ]
 [-3.0675387   0.32607555 -5.638299   -8.941689   -5.4401207 ]
 [-6.030264    9.6707535   3.6138897  -1.4670372   7.356718  ]
 [-7.345109    3.2823992   7.9516582  -1.2184887  -1.1138039 ]
 [ 9.794245    1.3192654   9.879135   -3.4744143   9.652384  ]], shape=(8, 5), dtype=float32)
tf.Tensor(
[[3.5321973e-05 1.3374809e-05 5.6229118e-04 3.5399295e-04 1.1489857e-03
  6.0549760e-01 3.4722216e-05 3.9235377e-01]
 [1.5509571e-03 2.8666967e-05 1.7435512e-02 1.7144867e-04 5.1456656e-05
  3.2995604e-02 3.1904321e-02 9.1586208e-01]
 [1.8006853e-03 1.0986595e-05 6.3644335e-02 8.2765549e-01 6.1372608e-05
  1.0428258e-01 3.8882271e-07 2.5441963e-03]
 [2.3789781e-01 2.1581878e-01 4.8313334e-04 6.6712245e-02 3.0460301e-01
  6.5432824e-02 3.64

# 3-5: Multi-class Classifiers

Code.3-5-1: Multi-class Classifiers

In [20]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense

class TestModel(Model):
    def __init__(self):
        super(TestModel,self).__init__()
        
        self.dense1 = Dense(units=8,activation="relu")
        self.dense2 = Dense(units=5,activation="relu")
        self.dense3 = Dense(units=3,activation="softmax")
    
    def call(self,X):
        print("X :{}\n{}\n".format(X.shape,X.numpy()))
        
        X= self.dense1(X)
        print("A1 :{}\n{}\n".format(X.shape,X.numpy()))
        
        X= self.dense2(X)
        print("A2 :{}\n{}\n".format(X.shape,X.numpy()))
        
        X= self.dense3(X)
        print("Y :{}\n{}\n".format(X.shape,X.numpy()))
        print("Sum of vectors: {}\n".format(tf.reduce_sum(X,axis = 1)))
        
        
model = TestModel()

X = tf.random.uniform(shape = (8,5),minval=-10,maxval=10)
Y = model(X)

X :(8, 5)
[[ 5.8201838   8.689625    6.29101    -6.4356256   7.0250244 ]
 [-3.067627   -4.575901   -5.185468    0.1555109  -3.6201859 ]
 [ 9.738228   -5.2151036   6.5975685  -7.008815    1.0058231 ]
 [-6.6605783   4.8422165   2.3565435  -1.8858051   6.9234505 ]
 [ 0.21056938  6.214506   -4.6397734   1.3649158  -1.6912384 ]
 [ 7.6004753   2.776003    3.707407    8.090155    4.5494843 ]
 [-2.4836159  -1.5401287   2.9075813  -3.5951638  -2.6777983 ]
 [-7.4796534   5.244734   -0.34971428 -6.8714285   8.38879   ]]

A1 :(8, 8)
[[ 6.5897384   0.          4.9387116   0.          5.728498    0.
   0.          0.        ]
 [ 0.          0.          0.          2.4021602   0.          0.76295394
   3.9392114   0.5909818 ]
 [ 6.969769    4.223093    0.          0.          0.          1.0489982
   0.          0.8475483 ]
 [ 0.          0.          0.          0.          0.4556886   0.
   0.          4.516868  ]
 [ 0.          0.          5.3609123   0.          2.967144    0.
   2.380903    0.   